### ISSUE TITLE
Help me with how to build

### ISSUE THREAD

**Issue by razcakappa** [elementary/wingpanel-indicator-network#90] opened 2018-04-18 04:07 UTC
I cloned the code and followed the README.md and started to `make` however `make` fails with 26 errors. I haven't build with Vala before. Can anyone help? Below attached the `make` output.

[log.txt](https://github.com/elementary/wingpanel-indicator-network/files/1922414/log.txt)

**Comment by danrabbit** [comment] 2018-04-18 04:30
You also need to build [wingpanel](https://github.com/elementary/wingpanel) from master since we now rely on the very latest API.

Closing because this is not a bug

**Closed by danrabbit** 2018-04-18 04:30 UTC

**Comment by razcakappa** [comment] 2018-04-18 04:34
@danrabbit Thanks a lot for the respond. Also can you mention about how is the folder configuration should be done. Should I clone all wingpanel related projects to single folder and make a build folder or should I build one  by one?

**Comment by tintou** [comment] 2018-04-18 08:48
each project can be built separately, starting with `wingpanel` itself

**Comment by razcakappa** [comment] 2018-04-18 08:55
@tintou I tried placing `wingpanel` and `winpanel-indicator-network` on same directory and first ran `cmake` and `make` on `wingpanel`. Its a success.

Then tried running `cmake` and `make` on `winpanel-indicator-network`, in that case `cmake` completes without any issues. However `make` getting failed with the following dump.

```
[  5%] Generating Indicator.c;Utils.c;Widgets/DisplayWidget.c;Widgets/PopoverWidget.c;Widgets/EtherInterface.c;Widgets/VpnInterface.c;Widgets/WifiInterface.c;Widgets/ModemInterface.c;common/Widgets/WifiMenuItem.c;common/Widgets/VpnMenuItem.c;common/Widgets/NMVisualizer.c;common/Widgets/WidgetNMInterface.c;common/rfkill.c;common/Widgets/AbstractWifiInterface.c;common/Widgets/AbstractVpnInterface.c;common/Widgets/AbstractEtherInterface.c;common/Widgets/AbstractModemInterface.c
warning: --save-temps has no effect when -C or --ccode is set
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:27.9-27.25: error: The name `caption' does not exist in the context of `Wingpanel.Widgets.Switch'
        wifi_item.caption = display_title;
        ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:29.13-29.29: error: The name `caption' does not exist in the context of `Wingpanel.Widgets.Switch'
            wifi_item.caption = display_title;
            ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:33.26-33.41: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            var active = wifi_item.active;
                         ^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:33.17-33.41: error: var declaration not allowed with non-typed initializer
            var active = wifi_item.active;
                ^^^^^^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:34.17-34.22: error: The name `active' does not exist in the context of `Network.WifiInterface.new._lambda10_'
            if (active != !software_locked) {
                ^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:35.67-35.72: error: The name `active' does not exist in the context of `Network.WifiInterface.new._lambda10_'
                rfkill.set_software_lock (RFKillDeviceType.WLAN, !active);
                                                                  ^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:36.49-36.54: error: The name `active' does not exist in the context of `Network.WifiInterface.new._lambda10_'
                nm_client.wireless_set_enabled (active);
                                                ^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/WifiInterface.vala:62.9-62.24: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
        wifi_item.active = !locked;
        ^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/EtherInterface.vala:27.13-27.33: error: The name `caption' does not exist in the context of `Wingpanel.Widgets.Switch'
            ethernet_item.caption = display_title;
            ^^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/EtherInterface.vala:33.17-33.36: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            if (ethernet_item.active) {
                ^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/EtherInterface.vala:52.13-52.32: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            ethernet_item.active = false;
            ^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/EtherInterface.vala:58.13-58.32: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            ethernet_item.active = false;
            ^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/EtherInterface.vala:63.13-63.32: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            ethernet_item.active = false;
            ^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/EtherInterface.vala:74.13-74.32: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            ethernet_item.active = true;
            ^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/EtherInterface.vala:80.13-80.32: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            ethernet_item.active = true;
            ^^^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/ModemInterface.vala:63.13-63.30: error: The name `caption' does not exist in the context of `Wingpanel.Widgets.Switch'
            modem_item.caption = display_title;
            ^^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/ModemInterface.vala:68.17-68.33: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            if (modem_item.active && device.state == NM.DeviceState.DISCONNECTED) {
                ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/ModemInterface.vala:70.25-70.41: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            } else if (!modem_item.active && device.state == NM.DeviceState.ACTIVATED) {
                        ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/ModemInterface.vala:88.17-88.33: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
                modem_item.active = false;
                ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/ModemInterface.vala:94.17-94.33: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
                modem_item.active = false;
                ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/ModemInterface.vala:104.17-104.33: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
                modem_item.active = true;
                ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/ModemInterface.vala:109.17-109.33: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
                modem_item.active = true;
                ^^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/VpnInterface.vala:24.9-24.24: error: The name `caption' does not exist in the context of `Wingpanel.Widgets.Switch'
        vpn_item.caption = display_title;
        ^^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/VpnInterface.vala:29.37-29.51: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            revealer.reveal_child = vpn_item.active;
                                    ^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/VpnInterface.vala:30.18-30.32: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            if (!vpn_item.active) {
                 ^^^^^^^^^^^^^^^
/home/stephan/projects/elementaryos/wingpanel-indicator-network/src/Widgets/VpnInterface.vala:63.13-63.27: error: The name `active' does not exist in the context of `Wingpanel.Widgets.Switch'
            vpn_item.active = true;
            ^^^^^^^^^^^^^^^
Compilation failed: 26 error(s), 1 warning(s)
src/CMakeFiles/network.dir/build.make:128: recipe for target 'src/network_valac.stamp' failed
make[2]: *** [src/network_valac.stamp] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/network.dir/all' failed
make[1]: *** [src/CMakeFiles/network.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tintou** [comment] 2018-04-18 08:57
You have to `sudo make install` wingpanel as it contains the library, making it a subfolder won't affect it at all.

**Comment by razcakappa** [comment] 2018-04-18 11:59
@tintou Thanks a lot for the support. That worked. First I thought installing libwingpanel would make the library available.
