### ISSUE TITLE
VPN empty connection on list

### ISSUE THREAD

**Issue by robsontenorio** [elementary/wingpanel-indicator-network#217] opened 2021-03-23 13:58 UTC
## What Happened

VPN empty connection icon on list.

## Expected Behavior

No empty connection on list.

## Steps to Reproduce

1. Create a new VPN connection
2. It will appear on list
3. But a new empty connection is added on network list

![image](https://user-images.githubusercontent.com/118955/112157998-82d95a00-8bc6-11eb-9705-1f60995c88ed.png)

## Platform Information
elementary OS 6 Early Access

**Comment by queeup** [comment] 2021-04-21 09:47
Duplicate of #195

**Comment by danirabbit** [comment] 2023-02-17 00:22
Seems like this was fixed in #230

**Closed by danirabbit** 2023-02-17 00:22 UTC
