### ISSUE TITLE
unable to connect to wifi if credentials are required

### ISSUE THREAD

**Issue by agriggio** [elementary/wingpanel-indicator-network#44] opened 2017-07-29 14:26 UTC
Hi,
I hope this is the right repository to report the issue.
Basically, I can't connect to an unknown (i.e. new) protected wifi network using the wingpanel indicator. I was expecting to get a dialog asking for credentials the first time I click on a protected network that is not known to the system, but nothing happens instead. I am using elementary 0.4.1 with all the updates. This was working fine on the previous version (freya).
Note that if I go through "Network Settings..." and click on an unknown protected network from there, then I do get the credentials dialog as expected

**Comment by danrabbit** [comment] 2020-09-08 21:07
Closing as a duplicate of #32

**Closed by danrabbit** 2020-09-08 21:07 UTC
