### ISSUE TITLE
Trying to connect to a WPA2 network opens network plug instead of asking for password.

### ISSUE THREAD

**Issue by arshubham** [elementary/wingpanel-indicator-network#101] opened 2018-07-04 04:18 UTC
OS: juno-beta1
Steps: 
1. Click on a secured network.
2. Instead of asking for password, it opens network plug and that too on Ethernet panel.

So I have to switch to WiFi panel and click on the network and type the password there.

**Comment by AlonsoEnrique** [comment] 2018-07-04 23:11
Same error here, test Juno beta 1 in live USB.

**Comment by cassidyjames** [comment] 2018-10-19 21:41
I don't seem to get this consistently, so I'm not sure what's causing it. We should see if we can reliably reproduce it.

**Comment by danrabbit** [comment] 2020-09-08 21:08
Closing as a duplicate of #32

**Closed by danrabbit** 2020-09-08 21:08 UTC
Labels: Status: Confirmed
