### ISSUE TITLE
Use device name instead of model name for ethernet tethering

### ISSUE THREAD

**Issue by kdwk** [elementary/wingpanel-indicator-network#239] opened 2021-10-19 07:39 UTC
### Problem

![Screenshot from 2021-10-19 15-34-15](https://user-images.githubusercontent.com/39268094/137864424-6a3f0b80-0f01-4333-bed6-68ebbf0b56f8.png)

The name of the model of my device is incorrect. It should be 'Apple iPad (6th generation)'. Moreover, if two devices of the same model is connected via USB and both are available for USB ethernet tethering, it would be impossible to tell which one is which.

### Proposal

Display the devices' name instead of its model name, like in Files:

![Screenshot from 2021-10-19 15-35-20](https://user-images.githubusercontent.com/39268094/137864767-47a8c2f3-354a-4293-859d-fce363eceb4a.png)

**Comment by danirabbit** [comment] 2023-02-16 21:30
We're using the disambiguation from Network Manager here now, so I can confirm that it'll show as either "USB Ethernet" or "Apple Ethernet". If it would better for it to always show "iPad Ethernet" or something like that, that should be pursued upstream in Network Manager: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues

Closing as "Out of scope" since device names come from Network Manager

**Closed by danirabbit** 2023-02-16 21:30 UTC
