### ISSUE TITLE
VPNs should have one toggle each, not a radio button

### ISSUE THREAD

**Issue by jlnr** [elementary/wingpanel-indicator-network#94] opened 2018-05-02 08:49 UTC
Right now, the VPN section of the indicator imitates the look of the Wi-Fi section: A global on/off toggle and a list (with radio buttons) of VPNs to choose from.

I don't think this UI makes sense for VPNs though. If I only have one VPN, should I use the global on/off switch or the radio button to enable/disable my VPN? And if I have several VPN connections, the radio buttons make it look like I can only connect to one at a time.

Suggestion: There should be no global VPN on/off toggle, but each VPN should have its own toggle or checkbox instead of a radio button.

**Comment by skewty** [comment] 2018-09-16 01:16
Related and may need to be considered during any potential fix:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/36

**Comment by danirabbit** [comment] 2023-02-16 21:49
Closing as a duplicate of #145 just because that report has screenshots

**Closed by danirabbit** 2023-02-16 21:49 UTC
