### ISSUE TITLE
connecting multiple vpn connections

### ISSUE THREAD

**Issue by JO0st** [elementary/wingpanel-indicator-network#160] opened 2020-07-08 10:31 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When multiple vpn connections are available it is impossible to connect to more than 1 of them using the network indicator. This is possible using the network preferences, but when this is done in this way it isn't shown in the network indicator. Only the one that was connected last is shown as connected. 

![afbeelding](https://user-images.githubusercontent.com/4729613/86906229-89e13a80-c113-11ea-9e26-92ccfdc73170.png)

### To Reproduce
1. create multiple vpn connections
2. connect to vpn connection 1 using the network indicator
3. connect to vpn connection 2 using the network indicator
4. notice that vpn connection 1 is disconnected, both in the network indicator and in the network preferences

### Expected behavior
vpn connection 1 should stay connected, and this is shown in the network indicator. 

### Screenshots or screen recordings

![screen recording](https://user-images.githubusercontent.com/4729613/86908485-de39e980-c116-11ea-93e9-5c6cef3811aa.gif)

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by auryn-macmillan** [comment] 2020-12-20 03:20
Came here to post this issue. It would be nice to be able to connect to multiple VPNs from the network indicator. Perhaps checkboxes or toggles, rather than radio buttons.

**Comment by danirabbit** [comment] 2023-02-17 00:22
Closing as a duplicate of #145

**Closed by danirabbit** 2023-02-17 00:22 UTC
